ouenze_app/models.py
from enum import unique
from sqlalchemy.orm import backref

from . import db

from flask_login import UserMixin

from sqlalchemy_utils import ChoiceType, PhoneNumberType, CountryType, PasswordType

from werkzeug.security import generate_password_hash, check_password_hash


class Utilisateur(UserMixin, db.Model):
    __tablename__ = "utilisateur"

    STATUS = [
    ('blank','----------'),
    ('vendeur', 'Vendeur'),
    ('client', 'Client')
]
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.String(64))
    prenom = db.Column(db.String(64))
    status = db.Column(ChoiceType(STATUS), default='blank')
    numero = db.Column(PhoneNumberType(region='CG'))
    adresse = db.Column(db.String(64))
    ville = db.Column(CountryType())
    #mot_de_passe = db.Column(PasswordType(
       # schemes=['pbkdf2_sha512']
    #))
    password = db.Column(db.String(254))
    boutique = db.relationship('Boutique', backref='utilisateur', uselist=False)

    def password_hash(self, password):
        self.password = generate_password_hash(password, method="sha256")

    def check_password(self, password):
        return check_password_hash(self.password, password)


    def __repr__(self):
        return '<utilisateur: {}>'.format(self.nom)



class Boutique(db.Model):

    CATEGORIE = [
    ('blank', '-----------------------'),
    ('electromenager', 'Eletromenager'),
    ('bricole', 'Bricole'),
    ('accessoire', 'Accessoire'),
    ('bijoux et colier', 'Bijoux et Colier'),
    ('telephone', 'Téléphone'),
    ('informatique', 'Matériel Informatique'),
    ('gadget', 'Gadgets'),
    ('consommable', 'Consommable Informatique'),
    ('beaute et soins', 'Beauté et Soin corporel')
]
    id = db.Column(db.Integer, primary_key=True)
    nom_boutique = db.Column(db.String(120), nullable=False)
    categorie = db.Column(ChoiceType(CATEGORIE), default='blank')
    adresse = db.Column(db.String(120), nullable=True)
    telephone = db.Column(PhoneNumberType(region='CG'))
    utilisateur_id = db.Column(db.Integer, db.ForeignKey('utilisateur.id'), unique=True)

    def __repr__(self):
        return '<boutique>: {}>'.format(self.nom_boutique)


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom_article = db.Column(db.String(120), nullable=False)
    prix = db.Column(db.String(30), nullable=False)
    quantite = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return '<article: {}>'.format(self.nom_article)

ouenze_app/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, SubmitField, StringField, IntegerField, validators, PasswordField
from wtforms.validators import DataRequired, EqualTo, Email
from wtforms_alchemy.fields import PhoneNumberField, CountryField

from .models import Utilisateur

class InscriptionForm(FlaskForm):
    nom = StringField('Nom', validators=[DataRequired()])
    prenom = StringField('Prénom', validators=[DataRequired()])
    status = SelectField('Status', choices=Utilisateur.STATUS)
    numero = PhoneNumberField('Téléphone', validators=[DataRequired()], region='CG', display_format='national')
    ville = CountryField('Pays')
    adresse = StringField('Adresse', validators=[DataRequired()])
    mot_de_passe = PasswordField('Mot de passe', validators=[DataRequired()])
    confirmation = PasswordField('Confirmation', validators=[EqualTo('mot_de_passe', message='mot de passe non identique')])
    valider = SubmitField('Inscription')


class ConnexionForm(FlaskForm):
    nom = StringField('Nom', validators=[DataRequired()])
    mot_de_passe = PasswordField('Mot de passe', validators=[DataRequired()])
    valider = SubmitField('Connexion')

ouenze_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def init_app():
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.Config')

#================= Zone d'initialisation des plugins ================#
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    
#================= Zone d'importation des parties de l'application ======================#
    with app.app_context():

        from . import models

        #===== Enregistrement des plans dans l'app ======#
        from .home.routes import home_bp
        from .boutique.routes import boutique_bp

        app.register_blueprint(home_bp)
        app.register_blueprint(boutique_bp)
        
        #====== creation tables dans la base de donnée ======#
        db.create_all()

        return app

ouenze_app/boutique/routes.py
from flask import Blueprint
from flask import redirect, render_template, url_for


boutique_bp = Blueprint(
    'boutique_bp', __name__,
    static_folder='static',
    template_folder='templates',
    url_prefix='/boutique',
    static_url_path='boutique/static'
)

@boutique_bp.route('/accueil')
def accueil():
    return render_template('boutique/accueil.html')

ouenze_app/home/routes.py
from flask import Blueprint
from flask import current_app as app
from flask import render_template, redirect, url_for, flash

from..forms import InscriptionForm, ConnexionForm

from ..models import Utilisateur, db

from flask_login import login_required,logout_user, current_user, login_user

from .. import login_manager    


#=============== Configuration de Blueprint ================#

home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/home/static'
) 

#=============== Zone des itineraires ====================#

@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return Utilisateur.query.get(user_id)
    return None

@home_bp.route('/')
def accueil():
    return render_template(
        'accueil.html'
    )

@home_bp.route('/inscription', methods=['GET', 'POST'])
def page_inscription():
    form = InscriptionForm()
    if form.validate_on_submit():
        deja_inscrit = Utilisateur.query.filter_by(nom=form.nom.data).first()
        if deja_inscrit is None:
            utilisateur = Utilisateur(
                nom=form.nom.data,
                prenom=form.prenom.data,
                status=form.status.data,
                numero=form.numero.data,
                adresse=form.adresse.data,
                ville=form.ville.data,
            )
            utilisateur.password_hash(form.mot_de_passe.data)
            db.session.add(utilisateur)
            db.session.commit()
            flash('votre enregistrement a été effectué avec success')
            return redirect(url_for('home_bp.page_connexion'))
        flash("Désolé ce nom d'utilisateur existe déjà !!")
    return render_template(
        'inscription.html',
        form=form
    )

@home_bp.route('/connexion', methods=["GET", "POST"])
def page_connexion():
    form = ConnexionForm()
    if form.validate_on_submit():
        user = Utilisateur.query.filter_by(nom=form.nom.data).first()
        if user and user.check_password(password=form.mot_de_passe.data):
            login_user(user)
            return redirect(url_for('home_bp.accueil'))
        return redirect(url_for('home_bp.page_connexion'))
    return render_template('connexion.html', form=form)


@home_bp.route('/deconnexion')
@login_required
def page_deconnexion():
    logout_user()
    return redirect(url_for('home_bp.accueil'))

ouenze_app/templates/layout/layout.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="author" content="Junior Batilat">
    <meta name="description" content="Zando application">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/foundation.css') }} ">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/app.css') }} ">
    <link rel="stylesheet" href=" {{ url_for('static', filename='font/css/all.css') }} ">
    {% block style %} {% endblock style %}
    
    {% if titre %}
        <title> {{ titre }} </title>
    {% else %}
        <title>Market</title>
    {% endif %}
</head>

<body>
<!-- #========= Barre de navigation =================# -->
    {% include 'partiels/navigation.html' %}

<!-- #========= Contenu des pages ===================# -->
    {% block content %} {% endblock content %}

<!-- #============== Pied de page ===================# -->
    {% include 'partiels/pied_de_page.html' %}

<!-- #============ Fichier Javascript ===============# -->
    <script src=" {{ url_for('static', filename='js/vendor/jquery.js') }} "></script>
    <script src=" {{ url_for('static', filename='js/vendor/what-input.js') }} "></script>
    <script src="{{ url_for('static', filename='js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

ouenze_app/templates/layout/layout_carroussel.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/foundation.css') }} ">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/app.css') }} ">
    <link rel="stylesheet" href=" {{ url_for('static', filename='font/css/all.css') }} ">
    {% if titre %}
    <title> {{ titre }} </title>
    {% else %}
    <title>WENZE Market</title>
    {% endif %}
</head>

<body>
    <!-- #========= Barre de navigation =================# -->
    {% include 'partiels/navigation.html' %}

    <!-- #========= Carroussel =================# -->
    {% include 'partiels/carroussel.html' %}

    <!-- #========= Contenu des pages ===================# -->
    {% block content %} {% endblock content %}

    <!-- #============== Pied de page ===================# -->
    {% include 'partiels/pied_de_page.html' %}

    <!-- #============ Fichier Javascript ===============# -->
    <script src=" {{ url_for('static', filename='js/vendor/jquery.js') }} "></script>
    <script src=" {{ url_for('static', filename='js/vendor/what-input.js') }} "></script>
    <script src="{{ url_for('static', filename='js/vendor/foundation.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</body>

</html>

ouenze_app/templates/partiels/carroussel.html
{% block carroussel %}
    <div class="grid-x">
        <div class="cell large-12 meduim-6">
            <div class="orbit" role="region" aria-label="Youtube Netflix Amazone" data-orbit>
                <div class="orbit-wrapper">
                    <div class="orbit-controls">
                        <button class="orbit-previous"><span class="show-for-sr">Previous
                                Slide</span>&#9664;&#xFE0E;</button>
                        <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
                    </div>
                    <ul class="orbit-container">
                        <li class="orbit-slide is-active">
                            <div class="orbit-1 orbit-figure">
                            </div>
                        </li>
                        <li class="orbit-slide">
                            <div class="orbit-2 orbit-figure">
                            </div>
                        </li>
                        <li class="orbit-slide">
                            <div class="orbit-3 orbit-figure">
                            </div>
                        </li>
                        <li class="orbit-slide">
                            <div class="orbit-4 orbit-figure">
                            </div>
                        </li>
                        <li class="orbit-slide">
                            <div class="orbit-5 orbit-figure">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock carroussel %}

ouenze_app/templates/partiels/navigation.html
<div class="nav-container">
    <div class="grid-x">
        <div class="cell large-12">
            <div class="grid-container fluid">
                <div class="padding-y">
                    <div class="grid-x align-middle grid-margin-x">
                        <div class="cell large-3">
                            <h4>WENZE Market</h4>
                        </div>
                        <div class="cell large-6">
                            <div class="input-group">
                                <span class="input-group-label">Catégorie</span>
                                <input class="input-group-field" type="text">
                                <div class="input-group-button">
                                    <input type="submit" class="button" value="Recherche">
                                </div>
                            </div>
                        </div>
                        <div class="cell large-3">
                            <ul class="menu align-center">
                                {% if current_user.is_authenticated %}
                                    <li><a href=""><i class=" fas fa-user-circle fa-lg"></i></a></li>
                                    <li><a href=""><i class="fas fa-shopping-basket fa-lg"></i></a></li>
                                    {% if current_user.status == 'vendeur' %}
                                        <li><a href=" {{ url_for('boutique_bp.accueil') }} "><i class=" fas fa-store fa-lg"></i></a></li>
                                    {% elif current_user.status == 'client' %}
                                        <li><a href=""><i class=" fas fa-user-cog fa-lg"></i></a></li>
                                    {% endif %}
                                    <li><a href=" {{ url_for('home_bp.page_deconnexion') }} "> <i class=" fas fa-sign-out-alt fa-lg "></i> </a></li>
                                {% else %}
                                    <li><a href=" {{ url_for('home_bp.page_connexion') }} "><i class="fas fa-user fa-lg"></i></a></li>
                                    <li><a href=""><i class="fas fa-shopping-bag fa-lg"></i></a></li>
                                    <li><a href=""><i class="fas fa-address-book fa-lg"></i></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>