ouenze_app/home/routes.py
from flask import Blueprint
from flask import current_app as app
from flask import render_template, redirect, url_for, flash

from..forms import InscriptionForm, ConnexionForm

from ..models import Utilisateur, db

from flask_login import login_required,logout_user, current_user, login_user

from .. import login_manager    


#=============== Configuration de Blueprint ================#

home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/home/static'
) 

#=============== Zone des itineraires ====================#

@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return Utilisateur.query.get(user_id)
    return None

@home_bp.route('/')
def accueil():
    return render_template(
        'accueil.html'
    )

@home_bp.route('/inscription', methods=['GET', 'POST'])
def page_inscription():
    form = InscriptionForm()
    if form.validate_on_submit():
        deja_inscrit = Utilisateur.query.filter_by(nom=form.nom.data).first()
        if deja_inscrit is None:
            utilisateur = Utilisateur(
                nom=form.nom.data,
                prenom=form.prenom.data,
                status=form.status.data,
                numero=form.numero.data,
                adresse=form.adresse.data,
                ville=form.ville.data,
            )
            utilisateur.password_hash(form.mot_de_passe.data)
            db.session.add(utilisateur)
            db.session.commit()
            flash('votre enregistrement a été effectué avec success')
            return redirect(url_for('home_bp.page_connexion'))
        flash("Désolé ce nom d'utilisateur existe déjà !!")
    return render_template(
        'inscription.html',
        form=form
    )

@home_bp.route('/connexion', methods=["GET", "POST"])
def page_connexion():
    form = ConnexionForm()
    if form.validate_on_submit():
        user = Utilisateur.query.filter_by(nom=form.nom.data).first()
        if user and user.check_password(password=form.mot_de_passe.data):
            login_user(user)
            return redirect(url_for('home_bp.accueil'))
        return redirect(url_for('home_bp.page_connexion'))
    return render_template('connexion.html', form=form)


@home_bp.route('/deconnexion')
@login_required
def page_deconnexion():
    logout_user()
    return redirect(url_for('home_bp.accueil'))

ouenze_app/home/templates/accueil.html
{% extends 'layout/layout_carroussel.html' %}

{% block content %}
<div class="corps">
    <div class="grid-x">
        <div class="cell large-12">
            <div class="categorie">
                <div class="grid-container fluid">
                    <div class="grid-x grid-margin-x align-justify">
                        <div class="cell large-3 meduim-3">
                            <div class="cat-1">
                                <p>
                                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea aspernatur dolore,
                                    tempora
                                    sunt
                                    rerum harum? Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis
                                    provident
                                    inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea
                                    aspernatur
                                    dolore,
                                    tempora sunt rerum harum?
                                    Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis provident
                                    inventore?
                                </p>
                            </div>
                        </div>
                        <div class="cell large-3 meduim-3">
                            <div class="cat-1">
                                <p>
                                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea aspernatur dolore,
                                    tempora
                                    sunt
                                    rerum harum? Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis
                                    provident
                                    inventore?Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea
                                    aspernatur
                                    dolore,
                                    tempora sunt rerum harum?
                                    Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis provident
                                    inventore?
                                </p>
                            </div>
                        </div>
                        <div class="cell large-3 meduim-3">
                            <div class="cat-1">
                                <p>
                                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea aspernatur dolore,
                                    tempora
                                    sunt
                                    rerum
                                    harum? Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis
                                    provident
                                    inventore?Lorem
                                    ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea aspernatur dolore,
                                    tempora
                                    sunt
                                    rerum
                                    harum?
                                    Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis provident
                                    inventore?
                                </p>
                            </div>
                        </div>
                        <div class="cell large-3 meduim-3">
                            <div class="cat-1">
                                <p>
                                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea aspernatur dolore,
                                    tempora
                                    sunt
                                    rerum
                                    harum? Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis
                                    provident
                                    inventore?Lorem
                                    ipsum dolor sit, amet consectetur adipisicing elit. Tenetur quod ea aspernatur dolore,
                                    tempora
                                    sunt
                                    rerum
                                    harum?
                                    Iste iure magni laboriosam veniam, repellendus quia. Soluta, nam? Hic veritatis provident
                                    inventore?
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ouenze_app/home/templates/connexion.html
{% extends 'layout/layout.html' %}

{% block style %}
<link rel="stylesheet" href=" {{ url_for('home_bp.static', filename='css/home_bp_css.css') }} ">
{% endblock style %}

{% block content %}
<div class="grid-container">
    <div class="grid-x">
        <div class="cell large-6 large-offset-3">
            <div class="container-formulaire">
                <div class="grid-x grid-padding-y gris">
                    <div class="cell large-12">
                        <h3 class="text-center">Formulaire de connexion</h3>
                    </div>
                </div>
                <div class="grid-container margin-container">
                    <div class="grid-x">
                        <div class="cell large-12">
                            <form action=" {{ url_for('home_bp.page_connexion') }} " method="POST">
                                {{ form.csrf_token }}

                                {% with messages = get_flashed_messages() %}
                                {% if messages %}
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        <div class="callout success" data-closable>
                                            {% for message in messages %}
                                            <p> {{ message }} </p>
                                            {% endfor %}
                                            <button class="close-button" aria-label="Dismiss alert" type="button"
                                                data-close>
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                {% endif %}

                                {% endwith %}

                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.nom.label }}
                                        {{ form.nom(placeholder='Votre nom') }}
                                        {% if form.nom.errors %}
                                        <ul class="errors">
                                            {% for error in form.nom %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.mot_de_passe.label }}
                                        {{ form.mot_de_passe(placeholder='Votre mot de passe') }}
                                        {% if form.mot_de_passe.errors %}
                                        <ul class="errors">
                                            {% for error in form.mot_de_passe %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.valider }}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="grid-x">
                        <div class="cell large-12">
                            <p>Vous n'avez pas de compte <a href=" {{ url_for('home_bp.page_inscription') }} ">Inscrivez-vous</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

ouenze_app/home/templates/inscription.html
{% extends 'layout/layout.html' %}

{% block style %}
    <link rel="stylesheet" href=" {{ url_for('home_bp.static', filename='css/home_bp_css.css') }} ">
{% endblock style %}

{% block content %}
   <div class="grid-container">
    <div class="grid-x">
        <div class="cell large-6 large-offset-3">
            <div class="container-formulaire">
                <div class="grid-x grid-padding-y gris">
                    <div class="cell large-12">
                        <h3 class="text-center">Formulaire d'inscription</h3>
                    </div>
                </div>
                <div class="grid-container margin-container">
                    <div class="grid-x">
                        <div class="cell large-12">
                            <form action=" {{ url_for('home_bp.page_inscription') }} " method="POST">
                                {{ form.csrf_token }}
                                
                                {% with messages = get_flashed_messages() %}
                                    {% if messages %}
                                        <div class="grid-x">
                                            <div class="cell large-12">
                                                <div class="callout alert" data-closable>
                                                    {% for message in messages %}
                                                        <p> {{ message }} </p>
                                                    {% endfor %}
                                                    <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}

                                {% endwith %}

                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.nom.label }}
                                        {{ form.nom(placeholder='Votre nom') }}
                                        {% if form.nom.errors %}
                                        <ul class="errors">
                                            {% for error in form.nom %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.prenom.label }}
                                        {{ form.prenom(placeholder='Votre prénom') }}
                                        {% if form.prenom.errors %}
                                        <ul class="errors">
                                            {% for error in form.prenom %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.status.label }}
                                        {{ form.status }}
                                        {% if form.status.errors %}
                                        <ul class="errors">
                                            {% for error in form.status %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.numero.label }}
                                        {{ form.numero(placeholder='Votre numero') }}
                                        {% if form.numero.errors %}
                                        <ul class="errors">
                                            {% for error in form.numero %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.ville.label }}
                                        {{ form.ville }}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.adresse.label }}
                                        {{ form.adresse(placeholder='Votre adresse') }}
                                        {% if form.adresse.errors %}
                                        <ul class="errors">
                                            {% for error in form.adresse %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.mot_de_passe.label }}
                                        {{ form.mot_de_passe(placeholder='Votre mot de passe') }}
                                        {% if form.mot_de_passe.errors %}
                                        <ul class="errors">
                                            {% for error in form.mot_de_passe %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.confirmation.label }}
                                        {{ form.confirmation(placeholder='Confirmer le mot de passe') }}
                                        {% if form.confirmation.errors %}
                                        <ul class="errors">
                                            {% for error in form.confirmation.errors %}
                                            <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="grid-x">
                                    <div class="cell large-12">
                                        {{ form.valider }}
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   </div>
{% endblock content %}

ouenze_app/home/templates/success.html
{% extends 'layout/layout.html' %}

{% block content %}
    <h1> Bravo vous êtes connecté </h1>
{% endblock content %}